#!/usr/bin/env python3
"""
Chatbot Project
Create a simple Discord bot for my gaming community
Generated by OOS
"""

from datetime import datetime


class ChatBot:
    def __init__(self):
        self.name = "OOS Bot"
        print(f"🤖 {self.name} initialized!")

    def respond(self, message: str) -> str:
        """Generate response to user message"""
        if "hello" in message.lower():
            return "Hello! How can I help you today?"
        elif "time" in message.lower():
            return f"Current time is {datetime.now().strftime('%H:%M:%S')}"
        else:
            return "I'm still learning! Can you rephrase that?"

    def run(self):
        """Main chat loop"""
        print("Chat started! Type 'quit' to exit.")
        while True:
            user_input = input("You: ")
            if user_input.lower() in ['quit', 'exit']:
                break
            response = self.respond(user_input)
            print(f"Bot: {response}")

if __name__ == "__main__":
    bot = ChatBot()
    bot.run()
